AWSTemplateFormatVersion: 2010-09-09
Description: Let admin in management account switch to child accounts
Resources:
    MgmtAccountAssumeRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: myadmin
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          AWS:
                              - arn:aws:iam::195527803861:root
                      Action:
                          - sts:AssumeRole
            Path: /
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AdministratorAccess
